### ISSUE TITLE
Trouble upgrading

### ISSUE THREAD

**Issue by p1r473** [Toilal/rebulk#21]
Hi,
I am having some trouble upgrading rebulk.

```
C:\WINDOWS\system32>pip3 install --upgrade rebulk
Collecting rebulk
  Using cached rebulk-2.0.1.tar.gz (258 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Temp\\pip-install-x7rrnnto\\rebulk\\setup.py'"'"'; __file__='"'"'C:\\Temp\\pip-install-x7rrnnto\\rebulk\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Temp\pip-pip-egg-info-z1ltmt0g'
         cwd: C:\Temp\pip-install-x7rrnnto\rebulk\
    Complete output (109 lines):
    zip_safe flag not set; analyzing archive contents...
    Traceback (most recent call last):
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Temp\easy_install-rxwatjqj\pytest-runner-5.2\setup.py", line 21, in <module>
        with io.open('rebulk/__version__.py', 'r') as f:
      File "c:\python3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 209, in run
        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 245, in zip_safe
        return analyze_egg(self.bdist_dir, self.stubs)
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 355, in analyze_egg
        safe = scan_module(egg_dir, base, name, stubs) and safe
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 395, in scan_module
        symbols = dict.fromkeys(iter_symbols(code))
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 414, in iter_symbols
        for name in code.co_names:
    AttributeError: type object 'StopIteration' has no attribute 'co_names'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Temp\pip-install-x7rrnnto\rebulk\setup.py", line 62, in <module>
        setup(**args)
      File "c:\python3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python3\lib\site-packages\setuptools\dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\python3\lib\site-packages\setuptools\dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\python3\lib\site-packages\pkg_resources\__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\python3\lib\site-packages\pkg_resources\__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "c:\python3\lib\site-packages\pkg_resources\__init__.py", line 1134, in obtain
        return installer(requirement)
      File "c:\python3\lib\site-packages\setuptools\dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\python3\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\python3\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\python3\lib\site-packages\setuptools\command\easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\python3\lib\site-packages\setuptools\command\easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\python3\lib\site-packages\setuptools\command\easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 251, in run_setup
        raise
      File "c:\python3\lib\contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\python3\lib\contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "c:\python3\lib\site-packages\pkg_resources\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Temp\easy_install-rxwatjqj\pytest-runner-5.2\setup.py", line 21, in <module>
        with io.open('rebulk/__version__.py', 'r') as f:
      File "c:\python3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 209, in run
        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 245, in zip_safe
        return analyze_egg(self.bdist_dir, self.stubs)
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 355, in analyze_egg
        safe = scan_module(egg_dir, base, name, stubs) and safe
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 395, in scan_module
        symbols = dict.fromkeys(iter_symbols(code))
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 414, in iter_symbols
        for name in code.co_names:
    AttributeError: type object 'StopIteration' has no attribute 'co_names'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by p1r473** [comment]
Same problem with a uninstallation and fresh install

```
C:\WINDOWS\system32>pip3 uninstall rebulk
Found existing installation: rebulk 1.0.0
Uninstalling rebulk-1.0.0:
  Would remove:
    c:\python3\lib\site-packages\rebulk-1.0.0.dist-info\*
    c:\python3\lib\site-packages\rebulk\*
Proceed (y/n)? y
  Successfully uninstalled rebulk-1.0.0

C:\WINDOWS\system32>pip3 install rebulk
Collecting rebulk
  Using cached rebulk-2.0.1.tar.gz (258 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Temp\\pip-install-2e_dk4qp\\rebulk\\setup.py'"'"'; __file__='"'"'C:\\Temp\\pip-install-2e_dk4qp\\rebulk\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Temp\pip-pip-egg-info-sp5x55kc'
         cwd: C:\Temp\pip-install-2e_dk4qp\rebulk\
    Complete output (109 lines):
    zip_safe flag not set; analyzing archive contents...
    Traceback (most recent call last):
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Temp\easy_install-ag4qiym6\pytest-runner-5.2\setup.py", line 21, in <module>
        with io.open('rebulk/__version__.py', 'r') as f:
      File "c:\python3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 209, in run
        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 245, in zip_safe
        return analyze_egg(self.bdist_dir, self.stubs)
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 355, in analyze_egg
        safe = scan_module(egg_dir, base, name, stubs) and safe
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 395, in scan_module
        symbols = dict.fromkeys(iter_symbols(code))
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 414, in iter_symbols
        for name in code.co_names:
    AttributeError: type object 'StopIteration' has no attribute 'co_names'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Temp\pip-install-2e_dk4qp\rebulk\setup.py", line 62, in <module>
        setup(**args)
      File "c:\python3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python3\lib\site-packages\setuptools\dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\python3\lib\site-packages\setuptools\dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\python3\lib\site-packages\pkg_resources\__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\python3\lib\site-packages\pkg_resources\__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "c:\python3\lib\site-packages\pkg_resources\__init__.py", line 1134, in obtain
        return installer(requirement)
      File "c:\python3\lib\site-packages\setuptools\dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\python3\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\python3\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\python3\lib\site-packages\setuptools\command\easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\python3\lib\site-packages\setuptools\command\easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\python3\lib\site-packages\setuptools\command\easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 251, in run_setup
        raise
      File "c:\python3\lib\contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\python3\lib\contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "c:\python3\lib\site-packages\pkg_resources\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "c:\python3\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Temp\easy_install-ag4qiym6\pytest-runner-5.2\setup.py", line 21, in <module>
        with io.open('rebulk/__version__.py', 'r') as f:
      File "c:\python3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 209, in run
        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 245, in zip_safe
        return analyze_egg(self.bdist_dir, self.stubs)
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 355, in analyze_egg
        safe = scan_module(egg_dir, base, name, stubs) and safe
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 395, in scan_module
        symbols = dict.fromkeys(iter_symbols(code))
      File "c:\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 414, in iter_symbols
        for name in code.co_names:
    AttributeError: type object 'StopIteration' has no attribute 'co_names'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by p1r473** [comment]
Fixed with
```
pip3 install --upgrade setuptools
```
